Update upload_statistics_preprod.yml
Setting exit 1 on death download failure in preprod action script

diff --git a/.github/workflows/upload_statistics_preprod.yml b/.github/workflows/upload_statistics_preprod.yml
--- a/.github/workflows/upload_statistics_preprod.yml
+++ b/.github/workflows/upload_statistics_preprod.yml
@@ -222,3 +222,8 @@ jobs:
         else
           echo "File for ${{env.file_death}} not available yet"
         fi
+        if [${{env.death_response}} != "200"]
+        then 
+          echo "death download failure"
+          exit 1
+        fi
